# Generated by Django 3.2.13 on 2022-04-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=230)),
                ('phonenumber', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
