# Generated by Django 3.2.13 on 2022-04-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_auto_20220417_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='countrya',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='state',
            new_name='item',
        ),
    ]
